### ISSUE TITLE
Retocar vista login

### ISSUE THREAD

**Issue by franncoronel** [LaraAReeves/UNSAM-Frontend#17]
Creo que el borde gris se podría eliminar haciendo que la box ocupe toda la pantalla en mobile.
![image](https://github.com/user-attachments/assets/0d1aafe0-f7b5-4a67-ae33-5f8e4415f822)

**Comment by MelOviedo** [comment]
Retoque el formato para tabletas y celular
![imagen](https://github.com/user-attachments/assets/1fa12d1a-cef3-45f4-ba43-6aa5928afd88)

mientras que el formato web quedo como estaba 
![imagen](https://github.com/user-attachments/assets/f5fd3f33-e9f8-49de-b335-c61a954e6caf)
